manifest:
  remotes:
    - name: github
      url-base: https://github.com/GarrettCarter-eaton
  projects:
    - name: west-quote-test-dep
      remote: github
      revision: branch-with-'-quote
self:
    path: west-quote-test-manifest
